name: Deploy Firestore rules

on:
  push:
    branches:
      - main
    paths:
      - 'firestore.rules'
      - 'firebase.json'
      - '.firebaserc'
      - '.github/workflows/deploy-firestore-rules.yml'
  workflow_dispatch:

jobs:
  deploy_rules:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Deploy Firestore rules
        uses: w9jds/firebase-action@v15.16.0
        with:
          args: deploy --only firestore:rules
        env:
          GCP_SA_KEY: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_ASCUITA }}'
